### ISSUE TITLE
IR Blaster

### ISSUE THREAD

**Issue by MethHeadAlert** [AICP/proprietary_vendor_htc#1]
Could we revert the commit that included taking out the ir blaster?

**Comment by semdoc** [comment]
Link for specific commit please .

**Comment by MethHeadAlert** [comment]
Commits on Oct 28, 2015
@intervigilium
hima: Clean up hima proprietary files

That commit deleted just more than a typical cleanup. A lot of functions that did work are not broken. Second part is in hima-common
